{% set name = "vizro-mcp" %}
{% set version = "0.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vizro_mcp-{{ version }}.tar.gz
  sha256: c083120b53aac1cea779be0f3a8412b1516e5a76b88924863ffab67b07acb261

build:
  entry_points:
    - vizro-mcp = vizro_mcp:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pydantic
    - python >={{ python_min }}
    - httpx >=0.28.1
    - mcp >=1.6.0
    - vizro >=0.1.46
    - click >=8.1.7
    # Refer to https://github.com/mckinsey/vizro/blob/main/vizro-mcp/pyproject.toml#L21
    # "pandas[html,parquet,excel]"
    - pandas
    # Refer to https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L68
    # html = ['beautifulsoup4>=4.12.3', 'html5lib>=1.1', 'lxml>=4.9.2']
    - beautifulsoup4 >=4.12.3
    - html5lib >=1.1
    - lxml >=4.9.2
    # excel = ['odfpy>=1.4.1', 'openpyxl>=3.1.2', 'python-calamine>=0.1.7', 'pyxlsb>=1.0.10', 'xlrd>=2.0.1', 'xlsxwriter>=3.2.0']
    - odfpy >=1.4.1
    - openpyxl >=3.1.2
    - python-calamine >=0.1.7
    - pyxlsb >=1.0.10
    - xlrd >=2.0.1
    - xlsxwriter >=3.2.0
    # parquet = ['pyarrow>=10.0.1']
    - pyarrow >=10.0.1

test:
  imports:
    - vizro_mcp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: MCP server to help create Vizro dashboards and charts
  home: https://vizro.mckinsey.com/
  dev_url: https://github.com/mckinsey/vizro
  doc_url: https://vizro.readthedocs.io/en/stable/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
